/**
 * Document registry + export helpers for CrimeGPT.
 *
 * Export strategy (no new dependencies, matching the existing report pattern
 * in caseHelpers.js which prints to PDF via the browser):
 *   - PDF   : open a print-ready window; the browser's print dialog saves PDF.
 *   - Print : same window, straight to the print dialog.
 *   - DOCX  : a Word-compatible HTML document served with the msword MIME and
 *             a .doc extension — Word/Google Docs open and convert it cleanly,
 *             so officers get an editable word-processor file with zero deps.
 *
 * Documents are authored in Markdown; a small, safe converter turns them into
 * clean HTML for export.
 */

export const DOCUMENT_CATALOG = [
  { id: 'fir', title: 'First Information Report (FIR)' },
  { id: 'charge_sheet', title: 'Charge Sheet' },
  { id: 'arrest_memo', title: 'Arrest Memo' },
  { id: 'remand_application', title: 'Remand Application' },
  { id: 'seizure_memo', title: 'Seizure Memo' },
  { id: 'medical_letter', title: 'Medical Examination Letter' },
  { id: 'court_letter', title: 'Letter to the Court' },
  { id: 'witness_notice', title: 'Witness Notice' },
  { id: 'investigation_summary', title: 'Investigation Summary' },
  { id: 'digital_evidence_report', title: 'Digital Evidence Report' },
]

export const DOC_TITLE = Object.fromEntries(DOCUMENT_CATALOG.map((d) => [d.id, d.title]))

function esc(text) {
  return String(text ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function inline(text) {
  // Order matters: escape first, then apply inline markdown.
  let t = esc(text)
  t = t.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  t = t.replace(/(^|[^*])\*([^*]+)\*/g, '$1<em>$2</em>')
  t = t.replace(/`([^`]+)`/g, '<code>$1</code>')
  return t
}

/** Minimal, safe Markdown → HTML for document export. */
export function markdownToHtml(md) {
  const lines = String(md || '').split(/\r?\n/)
  const out = []
  let listOpen = false
  let inCode = false

  const closeList = () => {
    if (listOpen) {
      out.push('</ul>')
      listOpen = false
    }
  }

  for (const raw of lines) {
    const line = raw.replace(/\s+$/, '')

    if (line.trim().startsWith('```')) {
      if (inCode) {
        out.push('</pre>')
        inCode = false
      } else {
        closeList()
        out.push('<pre>')
        inCode = true
      }
      continue
    }
    if (inCode) {
      out.push(esc(raw))
      continue
    }

    if (!line.trim()) {
      closeList()
      continue
    }

    const h = line.match(/^(#{1,6})\s+(.*)$/)
    if (h) {
      closeList()
      const level = h[1].length
      out.push(`<h${level}>${inline(h[2])}</h${level}>`)
      continue
    }

    if (/^\s*([-*])\s+/.test(line)) {
      if (!listOpen) {
        out.push('<ul>')
        listOpen = true
      }
      out.push(`<li>${inline(line.replace(/^\s*[-*]\s+/, ''))}</li>`)
      continue
    }

    if (/^\s*(-{3,}|\*{3,})\s*$/.test(line)) {
      closeList()
      out.push('<hr/>')
      continue
    }

    closeList()
    out.push(`<p>${inline(line)}</p>`)
  }
  closeList()
  if (inCode) out.push('</pre>')
  return out.join('\n')
}

const DOC_STYLES = `
  body{font-family:'Times New Roman',Georgia,serif;color:#111;margin:48px;line-height:1.55;font-size:14px}
  h1{font-size:20px;margin:0 0 6px;text-align:center}
  h2{font-size:15px;margin:22px 0 8px;border-bottom:1px solid #ccc;padding-bottom:3px}
  h3{font-size:14px;margin:16px 0 6px}
  p{margin:8px 0}
  ul{margin:8px 0;padding-left:22px}
  li{margin:3px 0}
  code{font-family:Consolas,monospace;background:#f3f3f3;padding:1px 4px;border-radius:3px;word-break:break-all}
  pre{background:#f6f8fa;border:1px solid #e2e8f0;padding:10px;border-radius:6px;white-space:pre-wrap;word-break:break-word;font-family:Consolas,monospace;font-size:12px}
  hr{border:none;border-top:1px solid #ccc;margin:16px 0}
  .doc-meta{text-align:center;color:#555;font-size:12px;margin-bottom:8px}
  .doc-foot{margin-top:36px;border-top:1px solid #ccc;padding-top:8px;color:#777;font-size:11px}
`

function buildHtml(title, markdown, { caseId } = {}) {
  return `<!doctype html><html><head><meta charset="utf-8"/>
    <title>${esc(title)}</title>
    <style>${DOC_STYLES}</style></head><body>
    <div class="doc-meta">CyberAid · CrimeGPT${caseId ? ` · ${esc(caseId)}` : ''} · ${new Date().toLocaleString()}</div>
    ${markdownToHtml(markdown)}
    <div class="doc-foot">Generated by CrimeGPT. AI-assisted draft — every detail must be verified by the investigating officer before official or judicial use.</div>
    </body></html>`
}

function openPrintWindow(html, { print = true } = {}) {
  const win = window.open('', '_blank', 'width=860,height=1000')
  if (!win) return false
  win.document.write(print ? html.replace('</body>', '<script>window.onload=function(){setTimeout(function(){window.print()},250)}</script></body>') : html)
  win.document.close()
  return true
}

export function exportPdf(title, markdown, opts = {}) {
  return openPrintWindow(buildHtml(title, markdown, opts), { print: true })
}

export function printDocument(title, markdown, opts = {}) {
  return openPrintWindow(buildHtml(title, markdown, opts), { print: true })
}

export function exportDocx(title, markdown, opts = {}) {
  const html = buildHtml(title, markdown, opts)
  const blob = new Blob(['\ufeff', html], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const safe = title.replace(/[^\w-]+/g, '_').slice(0, 60)
  a.download = `${opts.caseId ? opts.caseId + '-' : ''}${safe}.doc`
  a.click()
  URL.revokeObjectURL(url)
}

export function exportMarkdown(title, markdown, opts = {}) {
  const blob = new Blob([markdown], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const safe = title.replace(/[^\w-]+/g, '_').slice(0, 60)
  a.download = `${opts.caseId ? opts.caseId + '-' : ''}${safe}.md`
  a.click()
  URL.revokeObjectURL(url)
}
